FROM ubuntu:16.04
MAINTAINER lamozarax dev@xiaogu-tech.com

RUN apt-get update
RUN apt-get install -y postgresql postgresql-contrib vim


USER postgres
RUN    /etc/init.d/postgresql start &&\
  psql --command "CREATE DATABASE lms;" &&\
  psql --command "CREATE USER lmsuser WITH PASSWORD 'password';" &&\
  psql --command "ALTER ROLE lmsuser SET client_encoding TO 'utf8';" &&\
  psql --command "ALTER ROLE lmsuser SET default_transaction_isolation TO 'read committed';" &&\
  psql --command "ALTER ROLE lmsuser SET timezone TO 'UTC';" &&\
  psql --command "GRANT ALL PRIVILEGES ON DATABASE lms TO lmsuser;"

# Adjust PostgreSQL configuration so that remote connections to the
# database are possible.
RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/9.5/main/pg_hba.conf

# And add ``listen_addresses`` to ``/etc/postgresql/9.5/main/postgresql.conf``
RUN echo "listen_addresses='*'" >> /etc/postgresql/9.5/main/postgresql.conf


EXPOSE 5432
CMD ["/usr/lib/postgresql/9.5/bin/pcostgres", "-D", "/var/lib/postgresql/9.5/main", "-c", "config_file=/etc/postgresql/9.5/main/postgresql.conf"]
