FROM ubuntu:16.04
MAINTAINER lamozarax dev@xiaogu-tech.com

RUN apt-get update \
    && apt-get install -y nginx git postgresql postgresql-contrib python3 python3-pip ssh vim tzdata \
    && apt-get clean

RUN locale-gen en_US en_US.UTF-8
ENV LC_ALL="en_US.UTF-8"
RUN echo America/Los_Angeles | tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata

RUN ln -s /usr/bin/python3 /usr/bin/python
RUN ln -s /usr/bin/pip3 /usr/bin/pip
RUN pip install --upgrade pip

ENV SITENAME=learning.laioffer.com
ARG SITENAME=learning.laioffer.com

RUN mkdir -p /sites
ADD ./xiaogu-tech-laioffer-lms-v1.0.0929.tar.gz /sites/$SITENAME
WORKDIR /sites/$SITENAME

RUN pip install -r deploy_tools/requirements/staging.txt
ENV DJANGO_SETTINGS_MODULE=config.settings_staging

USER postgres
RUN    /etc/init.d/postgresql start &&\
  psql --command "CREATE DATABASE lms;" &&\
  psql --command "CREATE USER lmsuser WITH PASSWORD 'password';" &&\
  psql --command "ALTER ROLE lmsuser SET client_encoding TO 'utf8';" &&\
  psql --command "ALTER ROLE lmsuser SET default_transaction_isolation TO 'read committed';" &&\
  psql --command "ALTER ROLE lmsuser SET timezone TO 'UTC';" &&\
  psql --command "GRANT ALL PRIVILEGES ON DATABASE lms TO lmsuser;"

# Adjust PostgreSQL configuration so that remote connections to the
# database are possible.
RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/9.5/main/pg_hba.conf

# And add ``listen_addresses`` to ``/etc/postgresql/9.5/main/postgresql.conf``
RUN echo "listen_addresses='*'" >> /etc/postgresql/9.5/main/postgresql.conf

USER root

WORKDIR /sites/$SITENAME/source
ENV LMS_DB_HOST=localhost
ENV LMS_DB_PORT=
ENV LMS_DB_NAME=lms
ENV LMS_DB_USER=lmsuser
ENV LMS_DB_PWD=password

RUN echo $LMS_DB_USER
RUN    /etc/init.d/postgresql start &&\
python manage.py makemigrations &&\
python manage.py migrate &&\
python manage.py initdb

USER postgres

EXPOSE 5432
CMD ["/usr/lib/postgresql/9.5/bin/postgres", "-D", "/var/lib/postgresql/9.5/main", "-c", "config_file=/etc/postgresql/9.5/main/postgresql.conf"]
